package com.kct.tplusmcscenter.model.objects

object AppleSignInStr {
    const val AR_SA = "ar_SA"
    const val CA_ES = "ca_ES"
    const val CS_CZ = "cs_CZ"
    const val DA_DK = "da_DK"
    const val DE_DE = "de_DE"
    const val EL_GR = "el_GR"
    const val EN_GB = "en_GB"
    const val EN_US = "en_US"
    const val ES_ES = "es_ES"
    const val ES_MX = "es_MX"
    const val FI_FI = "fi_FI"
    const val FR_CA = "fr_CA"
    const val FR_FR = "fr_FR"
    const val HR_HR = "hr_HR"
    const val HU_HU = "hu_HU"
    const val ID_ID = "id_ID"
    const val IT_IT = "it_IT"
    const val IW_IL = "iw_IL"
    const val JA_JP = "ja_JP"
    const val KO_KR = "ko_KR"
    const val MS_MY = "ms_MY"
    const val NL_NL = "nl_NL"
    const val NO_NO = "no_NO"
    const val PL_PL = "pl_PL"
    const val PT_BR = "pt_BR"
    const val PT_PT = "pt_PT"
    const val RO_RO = "ro_RO"
    const val RU_RU = "ru_RU"
    const val SK_SK = "sk_SK"
    const val SV_SE = "sv_SE"
    const val TH_TH = "th_TH"
    const val TR_TR = "tr_TR"
    const val UK_UA = "uk_UA"
    const val VI_VI = "vi_VI"
    const val ZH_CN = "zh_CN"
    const val ZH_HK = "zh_HK"
    const val ZH_TW = "zh_TW"
}